on: [push]
jobs:
    job_go_checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-go@v6
              with:
                go-version-file: go.mod
            - name: Tidy go module
              run: |
                  go mod tidy
                  if [[ $(git status --porcelain) ]]; then
                    git diff
                    echo
                    echo "go mod tidy made these changes, please run 'go mod tidy' and include those changes in a commit"
                    exit 1
                  fi
            - name: Run gofumpt
              run: diff -u <(echo -n) <(go run mvdan.cc/gofumpt@@latest -d .)
            - name: Run go vet
              run: go vet ./...
    job_go_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-go@v6
              with:
                go-version-file: go.mod
            - name: Run Go test -race
              run: go test ./...  -v -race -timeout=1h